### PR TITLE
Simplify promise resolve/reject callbacks

### PR DESCRIPTION
**Pull request by timwis**
Thanks for putting this together! It got me to actually get going with ES6. Having worked with promises before, though, I noticed that these two lines could be even simpler, as the arguments will be passed along. Technically `catch()` will log an `xhr` object but I think the point gets across to the readers. [Here is a demo](http://codepen.io/timwis/pen/dGdeqo?editors=0011). Hope this is helpful.

### CODE REVIEW

**Comment by DrkSephy** [comment]
Thank you for putting this together, your demo is awesome too. I personally feel that the code samples in the readme already highlight the main idea of how to use promises and `Promise.all. It may be a question of semantics, but I'll leave this issue open and if others +1 it, I'll go ahead and merge it in.

**Comment by battaglr** [comment]
Hi! This new example is certainly simpler and easier to read. For me is a :+1: unless the current "extra" code makes it easier to illustrate the concept you're trying to communicate.

**Comment by sahat** [comment]
While this is a good and simple example on how to use promises, and @timwis's PR simplifies it even further, I feel like this is not the best showcase of promises; taking an existing promise-based function and wrapping it with another promise function.

IMHO, a better example would be to use a callback-, or a stream-based function to demonstrate the same concept.

**Comment by abogazy333** [comment]
Nice

**Comment by timwis** [comment]
Agreed - my suggestion is more of an efficiency thing than an explanatory thing, and the purpose of this repo is explanation. Thanks for the discussion.

**Pull request closed without merging**
